/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Frame3 extends javax.swing.JFrame {

    /**
     * Creates new form Frame3
     */
    public Frame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        Absen = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        HobyAnimator = new javax.swing.JCheckBox();
        HobyProgram = new javax.swing.JCheckBox();
        HobyDesigner = new javax.swing.JCheckBox();
        HobyTeknisi = new javax.swing.JCheckBox();
        RPL = new javax.swing.JRadioButton();
        TKJ = new javax.swing.JRadioButton();
        Submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Reset1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(Absen);
        Absen.setBounds(100, 80, 240, 30);
        getContentPane().add(Nama);
        Nama.setBounds(100, 40, 240, 30);

        HobyAnimator.setText("Animator");
        getContentPane().add(HobyAnimator);
        HobyAnimator.setBounds(100, 170, 100, 23);

        HobyProgram.setText("Programming");
        getContentPane().add(HobyProgram);
        HobyProgram.setBounds(100, 150, 100, 23);

        HobyDesigner.setText("Designer");
        getContentPane().add(HobyDesigner);
        HobyDesigner.setBounds(220, 170, 80, 23);

        HobyTeknisi.setText("Teknisi");
        getContentPane().add(HobyTeknisi);
        HobyTeknisi.setBounds(220, 150, 80, 23);

        btnGroup.add(RPL);
        RPL.setText("RPL");
        getContentPane().add(RPL);
        RPL.setBounds(100, 120, 60, 23);

        btnGroup.add(TKJ);
        TKJ.setText("TKJ");
        getContentPane().add(TKJ);
        TKJ.setBounds(170, 120, 60, 23);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(120, 200, 73, 23);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 246, 380, 120);

        jLabel1.setText("Absen");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 70, 50, 40);

        jLabel2.setText("Biodata Siswa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 10, 90, 20);

        jLabel3.setText("Hasil :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 230, 50, 14);

        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 120, 70, 20);

        jLabel5.setText("Hoby");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 160, 40, 20);

        jLabel6.setText("Nama");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 40, 40, 30);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(310, 200, 73, 23);

        Reset.setText("Reset Hasil");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset);
        Reset.setBounds(200, 200, 100, 23);

        Reset1.setText("Reset Inputan");
        Reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(Reset1);
        Reset1.setBounds(0, 200, 110, 23);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 390, 370);

        setBounds(0, 0, 410, 412);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String nama = Nama.getText();
        String absen = Absen.getText();
        String jurusan;
        String hoby="";

        //Untuk Radio Button
        if (RPL.isSelected())
        jurusan = "RPL";
        else if (TKJ.isSelected())
        jurusan = "TKJ";
        else
            jurusan = "";

        //Untuk CheckBox
        if (HobyProgram.isSelected())
        hoby+=HobyProgram.getText()+" ";
        if (HobyAnimator.isSelected())
        hoby+=HobyAnimator.getText()+" ";
        if (HobyTeknisi.isSelected())
        hoby+=HobyTeknisi.getText()+" ";
        if (HobyDesigner.isSelected())
        hoby+=HobyDesigner.getText()+" ";
        TA.append("Nama Siswa   : "+nama+"\n"+"Absen Siswa    : "+absen+"\n"+"Jurusan Siswa  : "+jurusan+"\n"+"Hoby Siswa      : "+hoby);
    }//GEN-LAST:event_SubmitActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        TA.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void Reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset1ActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        Absen.setText("");
        HobyAnimator.setSelected(false);
        HobyDesigner.setSelected(false);
        HobyProgram.setSelected(false);
        HobyTeknisi.setSelected(false);
        btnGroup.clearSelection();
    }//GEN-LAST:event_Reset1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JButton Exit;
    private javax.swing.JCheckBox HobyAnimator;
    private javax.swing.JCheckBox HobyDesigner;
    private javax.swing.JCheckBox HobyProgram;
    private javax.swing.JCheckBox HobyTeknisi;
    private javax.swing.JTextField Nama;
    private javax.swing.JRadioButton RPL;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Reset1;
    private javax.swing.JButton Submit;
    private javax.swing.JTextArea TA;
    private javax.swing.JRadioButton TKJ;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
